-- Gerado por scripts/generate-seed-sql.ts — não edite à mão.
-- As fotos apontam para /produtos/*.png (pasta public). Ao trocar por fotos novas pelo painel, elas vão pro Storage.

insert into products (slug, name, game, type, language, collection, price_cents, unit_label, package_contents, description, images, stock, availability, preorder_eta, featured, published, created_at) values
('booster-avulso-fogo-fantasmagorico', 'Booster Avulso Fogo Fantasmagórico', 'pokemon', 'booster', 'BR', 'Fogo Fantasmagórico', 1500, null, '1 booster lacrado', 'Booster avulso da coleção Fogo Fantasmagórico, edição nacional da Copag. Bom pra abrir na hora ou completar o fichário.', array['/produtos/booster-fogo-fantasmagorico.png']::text[], 48, 'pronta-entrega', null, true, true, '2026-09-18T10:00:00Z'),
('blister-quadruplo-escuridao-absoluta', 'Blister Quádruplo - Escuridão Absoluta', 'pokemon', 'blister-quadruplo', 'BR', 'Escuridão Absoluta', 5200, null, '4 boosters + 1 carta promocional (25 cartas)', 'Blister com 4 boosters de Megaevolução — Escuridão Absoluta e uma carta promocional à mostra na frente da embalagem.', array['/produtos/blister-quad-escuridao.png', '/produtos/escuridao-triple.png']::text[], 2, 'pronta-entrega', null, true, true, '2026-09-15T10:00:00Z'),
('combo-de-pacotes-escuridao-absoluta-ing', 'Combo de Pacotes - Escuridão Absoluta', 'pokemon', 'combo', 'ING', 'Escuridão Absoluta', 23900, null, 'Booster Bundle com 6 boosters', 'Combo de pacotes da versão em inglês (Pitch Black). Chama no WhatsApp se quiser saber a composição exata antes de fechar.', array['/produtos/combo-escuridao-ing.png']::text[], 5, 'pronta-entrega', null, false, true, '2026-09-12T10:00:00Z'),
('etb-colecao-treinador-avancado-caos-ascendente', 'ETB Coleção Treinador Avançado - Caos Ascendente', 'pokemon', 'etb', 'BR', 'Caos Ascendente', 31900, null, 'Boosters, sleeves, dados, marcadores e caixa organizadora', 'A Elite Trainer Box nacional de Caos Ascendente. Vem com boosters e tudo que precisa pra montar e organizar o deck.', array['/produtos/etb-caos-ascendente.png']::text[], 0, 'pronta-entrega', null, false, true, '2026-08-20T10:00:00Z'),
('booster-box-fogo-fantasmagorico', 'Booster Box - Fogo Fantasmagórico', 'pokemon', 'booster-box', 'BR', 'Fogo Fantasmagórico', 45900, null, '36 boosters', 'Caixa fechada de Fogo Fantasmagórico, lacrada de fábrica. Pra quem quer abrir em quantidade ou guardar lacrada.', array['/produtos/bb-fogo-fantasmagorico.png']::text[], 3, 'pronta-entrega', null, true, true, '2026-09-18T09:00:00Z'),
('box-colecao-mega-charizard-x-ex', 'Box Coleção - Mega Charizard X ex', 'pokemon', 'box-colecao', 'BR', 'Megaevolução', 39900, null, 'Carta promocional Mega Charizard X ex, boosters e acessórios', 'Box de coleção com a carta promocional do Mega Charizard X ex. Presente certo pra fã de Charizard.', array['/produtos/box-mega-charizard.png']::text[], 6, 'pronta-entrega', null, true, true, '2026-08-28T10:00:00Z'),
('caixa-de-booster-mega-dream-ex-jap', 'Caixa de Booster Mega Dream ex', 'pokemon', 'booster-box', 'JAP', 'Mega Dream ex', 89900, null, 'Caixa japonesa lacrada', 'Caixa japonesa de Mega Dream ex, em pré-venda. Reserva com sinal pelo WhatsApp ou pagamento total pelo site.', array['/produtos/mega-dream-jap.png']::text[], 8, 'pre-venda', '2026-10-30', true, true, '2026-09-20T10:00:00Z'),
('baralho-batalha-de-liga-dragapult-ex', 'Baralho Batalha de Liga - Dragapult ex', 'pokemon', 'deck', 'BR', 'Batalha de Liga', 15900, null, 'Deck de 60 cartas pronto pra jogar + acessórios', 'Deck competitivo pronto do Dragapult ex. Dá pra levar direto pra liga da loja.', array['/produtos/baralho-dragapult.png']::text[], 4, 'pronta-entrega', null, false, true, '2026-09-02T10:00:00Z'),
('deck-inicial-fabled-esmeralda-e-rubi', 'Deck Inicial Fabled - Esmeralda e Rubi', 'lorcana', 'deck', 'ING', 'Fabled', 34900, null, 'Deck inicial de 60 cartas', 'Deck inicial Esmeralda e Rubi da coleção Fabled. Bom ponto de partida pra entrar em Lorcana.', array['/produtos/deck-fabled.png', '/produtos/deck-fabled-2.png']::text[], 1, 'pronta-entrega', null, false, true, '2026-08-25T10:00:00Z'),
('booster-avulso-archazias-island', 'Booster Avulso Archazia''s Island', 'lorcana', 'booster', 'ING', 'Archazia''s Island', 2990, null, '1 booster de 12 cartas', 'Booster avulso de Archazia''s Island, em inglês.', array['/produtos/lorcana-booster.png']::text[], 24, 'pronta-entrega', null, false, true, '2026-09-10T10:00:00Z'),
('caixa-de-booster-archazias-island', 'Caixa de Booster Archazia''s Island', 'lorcana', 'booster-box', 'ING', 'Archazia''s Island', 80000, null, '24 boosters de 12 cartas', 'Caixa fechada de Archazia''s Island em pré-venda. Garante a sua antes de chegar.', array['/produtos/lorcana-bb.png']::text[], 4, 'pre-venda', '2026-10-17', false, true, '2026-09-19T10:00:00Z'),
('sleeve-100-unidades', 'Sleeve (100 un.)', null, 'acessorio', null, null, 1600, null, 'Pacote com 100 sleeves tamanho padrão', 'Sleeve tamanho padrão (serve em Pokémon, Lorcana e One Piece). Protege o deck do dia a dia.', array['/produtos/sleeve.png']::text[], 60, 'pronta-entrega', null, false, true, '2026-07-10T10:00:00Z'),
('toploader-semi-rigido', 'Toploader Semi Rígido', null, 'acessorio', null, null, 350, 'a unidade', '1 toploader semi rígido', 'Toploader pra guardar carta boa ou mandar pra graduação. Vendido por unidade — coloca a quantidade no carrinho.', array[]::text[], 200, 'pronta-entrega', null, false, true, '2026-07-10T09:00:00Z'),
('playmat-viper-3mm-61x35', 'Playmat Viper 3mm 61x35cm', null, 'acessorio', null, null, 9900, null, 'Playmat de borracha 3mm, 61x35cm', 'Playmat de 3mm com base emborrachada, tamanho padrão de torneio.', array[]::text[], 0, 'esgotado', null, false, true, '2026-07-01T10:00:00Z'),
('booster-avulso-one-piece-exemplo', 'Booster Avulso One Piece (exemplo)', 'one-piece', 'booster', 'ING', 'Coleção a definir', 3500, null, '1 booster de 12 cartas', 'Produto de exemplo em rascunho. Edite nome, coleção, preço e foto antes de publicar.', array[]::text[], 20, 'pronta-entrega', null, false, false, '2026-09-21T10:00:00Z'),
('booster-box-one-piece-exemplo', 'Booster Box One Piece (exemplo)', 'one-piece', 'booster-box', 'JAP', 'Coleção a definir', 75000, null, '24 boosters', 'Produto de exemplo em rascunho. Edite nome, coleção, preço e foto antes de publicar.', array[]::text[], 3, 'pre-venda', '2026-11-14', false, false, '2026-09-21T09:00:00Z'),
('starter-deck-one-piece-exemplo', 'Starter Deck One Piece (exemplo)', 'one-piece', 'deck', 'ING', 'Coleção a definir', 12900, null, 'Deck de 51 cartas (50 + líder)', 'Produto de exemplo em rascunho. Edite nome, coleção, preço e foto antes de publicar.', array[]::text[], 0, 'esgotado', null, false, false, '2026-09-21T08:00:00Z')
on conflict (slug) do nothing;

-- Eventos de exemplo: ajuste ou apague pelo painel.
insert into events (title, kind, game, starts_at, description, entry_fee_cents, published) values
('Liga Pokémon TCG', 'liga', 'pokemon', '2026-09-26T14:00:00-03:00', 'Liga semanal no formato Padrão. Traz o deck; tem mesa pra quem quiser só treinar.', null, true),
('Liga Lorcana', 'liga', 'lorcana', '2026-10-01T19:00:00-03:00', 'Partidas casuais e ranqueadas de Lorcana. Iniciante é bem-vindo, a gente empresta deck.', null, true),
('Campeonato Pokémon — Escuridão Absoluta', 'campeonato', 'pokemon', '2026-10-11T13:00:00-03:00', 'Torneio suíço com premiação em boosters. Inscrição na loja ou pelo WhatsApp.', 3000, true);
